---
title: "Table A5 Cold Replication & Extension"
author: "Yue Lin"
date: "2022/4/17"
output: pdf_document
---

```{r}

# table A.5 cold replications

library(dplyr)
library(lfe)
library(tidyverse)
library(data.table)
library(stargazer)
pnl_dt_a5 <- readRDS("../original reproduction package/replication/data/did-gdelt.rds")
pnl_dt_a5 <- pnl_dt_a5[is.na(mean_sources_protest) == F]

brdr_dt <- readRDS("../original reproduction package/replication/data/did-gdelt-border.rds")
brdr_dt <- brdr_dt[is.na(mean_sources_protest) == F]

#================================================================
# Functions to estimate models and extract relevant information for regression table:

DiD <- function(dv = "ind_protest", iv = "ind_mine",
  unit_fe = "cell_number_5x5", time_fe = "year",  
  cl_var = "cell_number_5x5", dt = pnl_dt_a5) {
  
  form <- paste(dv, "~", iv, "|", unit_fe, "+", time_fe, 
    "| 0 |", cl_var) %>%
    as.formula()
  
  felm(form, data = dt, keepCX = FALSE)
}

Models <- function(y = "ind_protest") {
  m_list <- list()
  
  m_list[[1]] <- DiD(dv = y)
  m_list[[2]] <- DiD(dv = y, time_fe = "country_year")
  m_list[[3]] <- DiD(dv = y, unit_fe = "cell_period")
  m_list[[4]] <- DiD(dv = y, time_fe = "area_year", dt = brdr_dt)
  m_list[[5]] <- DiD(dv = y, time_fe = "area_year", dt = brdr_dt[border < 3])
  m_list[[6]] <- DiD(dv = y, iv = "placebo", time_fe = "country_year")
  m_list[[7]] <- DiD(dv = y, iv = "placebo", time_fe = "area_year", 
    dt = brdr_dt[border < 3])
  
  m_list
}

#================================================================

m_list <- Models(y = "mean_articles_protest")

# tbl_info <- TableInfo(m_list)

col_names <- c("Full", "Full", "Full",
  "Border", "Border$\\leq$2",
  "Full", "Border$\\leq$2")

t1 <- stargazer(m_list,
  covariate.labels = c("$D_{it}$", "$P_{it}$ (Placebo)"),
  dep.var.labels = c("Mean(Articles/Protest)", ""),
  column.labels = col_names,
  keep.stat = "n",
  table.placement = "ht!", column.sep.width = "0pt",
  digits = 2,
  title = "Mining Activity and Media Coverage",
  label = "tab:did_gdelt_media")

t_top <- t1[grep("ht!", t1):(grep("^Observations", t1) - 1)]

rm(m_list); gc()

#================================================================

m_list_s <- Models(y = "mean_sources_protest")

# tbl_info <- TableInfo(m_list)

t2 <- stargazer(m_list_s,
  covariate.labels = c("$D_{it}$", "$P_{it}$ (Placebo)"),
  dep.var.labels = c("Mean(Sources/Protest)", ""),
  keep.stat = "n",
  # add.lines = tbl_info,
  star.cutoffs = c(.1, .05), star.char = c("\\dagger", "*"),
  # notes = tbl_note,
  notes.append = FALSE,
  table.placement = "ht!", column.sep.width = "0pt",
  digits = 2)

t_bottom <- t2[c(grep("Dependent variable", t2):(grep("Dependent variable", t2) + 2),
  grep("^ \\$D", t2):length(t2))]

```

```{r}

# columns 1 and 4 of panel B in Table A5 - results significant in replication!

# We found that the SE in panel B of Table A5 is not correct: all SE are over reported. Note that panel A and B share the same codes, and no issue is found in panel A. This indicates that the problem is not with coding but with result reporting. Comparing mining cells with non-mining cells both in all samples (column 1 of Panel B) and in immediately surrounding border areas (column 4 of Panel B), we find the effect of mining to be negative and significant in these two models. Therefore, we find it possible that the reporting bias is one mechanism that moderates the effect of mining on reducing conflicts.

model2_1 <- felm(mean_sources_protest ~ ind_mine | cell_number_5x5 + year
               | 0 | cell_number_5x5, data = pnl_dt_a5) 
# it is negatively significant at 90% level!
summary(model2_1)

model2_4 <- felm(mean_sources_protest ~ ind_mine | cell_number_5x5 + area_year
               | 0 | cell_number_5x5, data = brdr_dt) 
# it is negatively significant at 99% level!
summary(model2_4)


```

